### ISSUE TITLE
Adding findbugs plugin and repairing maintainability bugs

### ISSUE THREAD

**Issue by lycantroph** [tomi936/outlay#4]
I added the plugin FindBugs, for the purpose of finding and repairing code malformations and inconsistencies.

**Comment by lycantroph** [comment]
I deleted random objects that were used only once.

**Comment by lycantroph** [comment]
Other bugs made no sense, "repairing" would make the code unreadable.

**Comment by zsomii** [comment]
OK.

**Comment by micskeiz** [comment]
OK

**Comment by micskeiz** [comment]
Adding the .idea folder is not a good idea. Please check, if you really need it in version control.
